@admin_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4NDQwNjl9.MElNxevOIugNe1jYNEk9mJD5AM8oXyR0MwXuUY1YfSQ

### requests products index
GET http://localhost:3000/products.json
Authorization: 

### requests products show
GET http://localhost:3000/products/1.json

### requests create product
POST http://localhost:3000/products.json
Authorization: Bearer {{admin_jwt}}
Content-Type: application/json

{
  "name": "Unicorn Blood", 
  "price": "250",   
  "description": "This is the purest substance in all of the world.",
   "image_url": "https://static.wikia.nocookie.net/harrypotter/images/2/26/Unicorn_blood.png/revision/latest?cb=20210418214529",
  "supplier_id": 2,    
  "quantity": 0,
  "availability": true,
  "inventory": 2
  }

### request update product

PATCH http://localhost:3000/products/20.json
Content-Type: application/json

{
  "image_url": "https://www.gastronomblog.com/wp-content/uploads/2020/10/Halloween-Cocktail-Unicorn-Blood-3.jpg"
}

### request delete product

DELETE http://localhost:3000/products/25.json




### requests supplier show
GET http://localhost:3000/supplier/2.json


### requests create user
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin2",
  "email": "admin2@test.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": "true"
}


### request session create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

### orders show request
GET http://localhost:3000/orders/17.json
Authorization: Bearer {{admin_jwt}}

### orders index request
GET http://localhost:3000/orders.json
Authorization: Bearer {{admin_jwt}}


### orders create request
POST http://localhost:3000/orders.json
Authorization: Bearer {{admin_jwt}}
Content-Type: application/json

{
  "product_id": 5,
  "quantity": 1
}