### requests products index
GET http://localhost:3000/products.json

### requests products show
GET http://localhost:3000/products/2.json

### requests post product
POST http://localhost:3000/products.json
Content-Type: application/json

{
  # "name": "test title", 
  "price": 50,   
  # "description": "test description",  
  # "image_url": "test image_url",  
  # "availability": "test directions"
  }

### request update product

PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
  "price": 8,
}

### request delete product

DELETE http://localhost:3000/products/18.json
